server:
  port: 8081

spring:
  aop:
    auto: true
  application:
    name: wgs-extend-demo-dubbo-provider



embedded:
  zookeeper:
    port: 2181

dubbo:
  protocol:
    name: dubbo
  scan:
    base-packages: com.wgs.extend.demo.service.impl
  service:
    version: 1.0
  registry:
    address: zookeeper://172.20.32.252:${embedded.zookeeper.port}
    # 缓存 把注册信息缓存起来， 服务重启时 保证可靠性！
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache