server:
  port: 8080

spring:
  aop:
    proxy-target-class: true
    auto: true
  application:
    name: wgs-extend-demo




#mybatis plus 设置
mybatis-plus:
#  mapper-locations: classpath*:com/wgs/extend/demo/mapper/xml/*Mapper.xml
  mapper-locations: classpath*:mybatis/xml/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型，自增
      id-type: AUTO
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

