#spring.datasource.url=jdbc:mysql://172.20.32.253:3308/eajucloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=anbang@123

#spring.dubbo.application.name=demo
#spring.dubbo.registry.address=172.20.32.252:2181
#spring.dubbo.protocol.name=dubbo
#spring.dubbo.protocol.port=20880
#spring.dubbo.scan=com.eaju.system.api

#wgs.extend.lock.path=/distributed-lock/

server:
  port: 8080

spring:
  application:
    name: wgs-extend-demo
  dubbo:
    registry:
      address: 172.20.32.252:2181

