#spring.datasource.url=jdbc:mysql://172.20.32.253:3308/eajucloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=anbang@123

server:
  port: 8080

spring:
  application:
    name: wgs-extend-demo

wgs:
  extend:
    object_pool:
      minIdle: 0
      maxIdle: 8
      maxTotal: 32
      testOnCreate: false
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
      blockWhenExhausted: true
      maxWaitMillis: 5000
      minEvicTime: 60000
      timeBetEvicRun: 300000
    fdfs:
      charSet: UTF-8
      trackerServers: 172.20.32.252:22122,172.20.32.252:22122
      trackerHttpPort: 80
      connectTimeout: 10000
      networkTimeout: 30000
      antiStealToken: false
      httpSecretKey: FastDFS1234567890
    lock:
      zk:
        url: 172.20.32.252:2181
        lockPath: /distributed-lock/
      redis:
        url: redis://172.20.32.252:6379
